# Copyright (c) 2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Uncomment these lines below to enable encoders.
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the line below to enable RGB.
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Enable CDC ACM for USB console
# CONFIG_USB_DEVICE_STACK=y
# CONFIG_USB_CDC_ACM=y
# CONFIG_SERIAL=y
# CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y
# CONFIG_UART_LINE_CTRL=y

# USB logging
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG=y

# Basic USB config
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n
CONFIG_BT=n

# All other settings should be in config/serene65.conf to avoid conflicts